### PR TITLE
buildtools bins for linux

### PR DESCRIPTION
**Pull request by ksanislo**
Mind including the linux bins so the make works in my environment as well?

### CODE REVIEW

**Comment by Wolvan** [comment]
Do these work as expected? Don't have a linux VM set up right now so I can't really test myself but I'll trust your word if you say they do

**Comment by Wolvan** [comment]
Actually, could you do me a favor and try moving the files into this folder structure
image
and try using [this makefile](https://gist.github.com/Wolvan/5105d7a39f71acfcf47e41b7da643b43)? See if that still builds properly for you, your changes are giving windows users a bit of trouble, I want to see if the folder structure and makefile edits give cross compatibility here

**Comment by ksanislo** [comment]
That all looks good from this end...

```
$ make
Cleaning up previous builds
rm -rf build
Making build directory structure
mkdir build
mkdir build/tmp
Making banner
buildtools/UNIX/bannertool makebanner -i "assets/banner.png" -ca "assets/audio.cwav" -o "build/tmp/banner.bin"
Created banner "build/tmp/banner.bin".
buildtools/UNIX/bannertool makesmdh -i "assets/icon.png" -s "Homebr3w" -l "Homebrew Browser for 3ds" -p "Wolvan" -o "build/tmp/icon.bin"
Created SMDH "build/tmp/icon.bin".
Making romfs
buildtools/UNIX/3dstool -cvtf romfs "build/tmp/romfs.bin" --romfs-dir "script"
load: script/index.lua
Building .3ds
buildtools/UNIX/makerom -f cci -o "build/Homebr3w.3ds" -rsf "buildtools/workarounds/3ds_workaround.rsf" -target d -exefslogo -elf "buildtools/lpp3ds/lpp-3ds.elf" -icon "build/tmp/icon.bin" -banner "build/tmp/banner.bin" -romfs "build/tmp/romfs.bin"
Building .cia
buildtools/UNIX/makerom -f cia -o "build/Homebr3w.cia" -elf "buildtools/lpp3ds/lpp-3ds.elf" -rsf "buildtools/workarounds/cia_workaround.rsf" -icon "build/tmp/icon.bin" -banner "build/tmp/banner.bin" -exefslogo -target t -romfs "build/tmp/romfs.bin"
Building .3dsx
rm -rf build/Homebr3w
cp -r "script" "build/Homebr3w"
cp "build/tmp/icon.bin" "build/Homebr3w/Homebr3w.smdh"
cp "buildtools/lpp3ds/lpp-3ds.3dsx" "build/Homebr3w/Homebr3w.3dsx"
Packing .3dsx as .tar
mkdir "build/tmp/3ds"
cp -r "build/Homebr3w" "build/tmp/3ds"
tar cf "build/Homebr3w.3dsx.tar" -C "build/tmp" 3ds
rm -rf "build/tmp/3ds"
Cleaning up temp files
rm -rf "build/tmp"
mkdir build/tmp
```

**Comment by Wolvan** [comment]
Merged, thanks a lot. Bet a bunch of linux people are going to welcome this change

**Comment by ksanislo** [comment]
Definitely! There's also osx bins of the tools as well, but I can't really test those since I've never bothered getting things configured for compiling locally. As soon as I got http based installs working on the 3DS, I switched to compiling remotely on my build server and just using AutoLoader to download/install/launch the cia with a single click on the 3ds.

**Comment by Wolvan** [comment]
Well, the build tools thing should be easily extendable for people who want to build on OSX. Make OSX folder, add a PLATFORM = OSX in the if statement at the top of the makefile and you should be golden

**Pull request merged**
